[build]
  publish = "."
  command = ""

#  Serve your real config.yml (so CMS can read it)
[[redirects]]
  from = "/admin/config.yml"
  to   = "/admin/config.yml"
  status = 200

#  Then catch all other /admin/* routes and send to the CMS entrypoint
[[redirects]]
  from   = "/admin/*"
  to     = "/admin/index.html"
  status = 200
  force  = true
