backend:
  name: git-gateway
  branch: main

media_folder: "uploads"       # Where your images get committed
public_folder: "/uploads"     # How they’re referenced in <img src>

media_library:
  name: uploadcare           # Built-in widget for image uploads
  config:
    publicKey: "demopublickey"

collections:
  - name: "photos"
    label: "Gallery"
    folder: "uploads"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
