backend:
  name: git-gateway
  branch: main

media_folder: "uploads"       # where your images go in the repo
public_folder: "/uploads"     # how they’re referenced in src= paths

media_library:
  # you can sign up at https://uploadcare.com to get your own key,
  # or use the demo key below for testing (not for production!)
  name: uploadcare
  config:
    publicKey: "demopublickey"

collections:
  - name: "photos"
    label: "Gallery"
    folder: "uploads"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
